# -*- coding: utf-8 -*-
"""Despliegue-AtaqueCorazon con Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lNkMaJAX-Uu_1hlJmPAhn_qmGlwEwS5

# Despliegue

- Cargamos el modelo
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import pickle
filename = 'modelo-class.pkl'
modelo, labelencoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de Ataques de corazón')

age = st.slider('age', min_value=1, max_value=82, value=20, step=1)
hypertension = st.selectbox('hypertension', ["Yes", "No"])
heart_disease = st.selectbox('heart_disease', ["Yes", "No"])
ever_married  = st.selectbox('ever_married ', ["Yes", "No"])
avg_glucose_level = st.number_input('avg_glucose_level', min_value=51.12, max_value=271.74)
smoking_status = st.selectbox('smoking_status', ["Yes", "No"])



#Dataframe
datos = [[age,hypertension,heart_disease,ever_married,avg_glucose_level,smoking_status,stroke_ataque_corazon]]
data = pd.DataFrame(datos, columns=['age','hypertension','heart_disease','ever_married','avg_glucose_level','smoking_status']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['age','hypertension','heart_disease','ever_married','avg_glucose_level','smoking_status'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
variables_numericas=['age','avg_glucose_level']
data_preparada[variables_numericas]= min_max_scaler.transform(data_preparada[variables_numericas])
data_preparada.head()

"""#**Predicciones**"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

# Recordar medida de error del modelo

st.warning("El modelo tiene un área bajo la curva ROC de 0.83")
